pipeline {
  agent {
    kubernetes {
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.11-1
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["/busybox/cat"]
    tty: true
"""
    }
  }
  tools {
    maven 'M3'
  }
  environment {
    MAVEN_OPTS = '-Xmx2048m -Xms256m'   // 최대 2GB
    REGISTRY = '172.16.0.194:5000'
    APP_NAME = 'h-cms'
    IMAGE = "${REGISTRY}/${APP_NAME}:${env.BUILD_NUMBER}"
    IMAGE_LATEST = "${REGISTRY}/${APP_NAME}:latest"
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build WAR') {
      steps {
        sh 'mvn clean package -DskipTests'
        sh 'cp humanframe.web/target/*.war app.war'
      }
    }
    stage('Docker Build & Push (Kaniko)') {
      steps {
        container('kaniko') {
          sh """
            /kaniko/executor \\
            --context ${env.WORKSPACE} \\
            --dockerfile ${env.WORKSPACE}/Dockerfile \\
            --destination ${env.IMAGE} \\
            --destination ${env.IMAGE_LATEST} \\
            --insecure \\
            --skip-tls-verify
          """
        }
      }
    }
  }
  post {
    always {
      cleanWs()
    }
  }
}
